### ISSUE TITLE
When trying to edit Super Admin Profile (Attempt to read property "emp_date" on null)

### ISSUE THREAD

**Issue by jvivas-rock** [4jean/lav_sms#34]
That happens while I'm logged with Super Admin account and I just tried to edit the profile because photo is not working and while I press that option, that exception is happening

**Comment by yungifez** [comment]
Can you post a full screenshot of the error to know where exactly the error is coming from

**Comment by jvivas-rock** [comment]
And also there is a problem with the 'Edit' form. I'm selecting the State but the program does not load the LGAs.

**Comment by jvivas-rock** [comment]
> Can you post a full screenshot of the error to know where exactly the error is coming from

src: /resources/views/pages/support_team/users/edit.blade.php
![image](https://user-images.githubusercontent.com/20029198/140250829-857ef288-c4cf-436a-83c2-900a1b383c7a.png)

**Comment by yungifez** [comment]
Ok i've found the problem which is not really a problem

on seeding,  some staff are added but associated staff records are not made with those staff

same case with students etc 

but the code tries to look for those properties

Now there's no solution to this problem except to create another staff youll test with instead of the default staff added during seeding


Try creating a new set of users and students that you'll perform your tests on instead of the seeded ones 

you might also encounter problems like these when you try to batch fix students exam records  etc

**Comment by yungifez** [comment]
sorry for the late reply

**Comment by 4jean** [comment]
> Ok I have found the problem which is not really a REAL WORLD problem
> 
> on seeding, some staff are added but associated staff records are not made with those staff
> 
> same case with students etc
> 
> but the code tries to look for those properties
> 
> Now there's no solution to this problem except to create another staff you'll test with instead of the default staff added during seeding
> 
> Try creating a new set of users and students that you'll perform your tests on instead of the seeded ones
> 
> you might also encounter problems like these when you try to batch fix students exam records and so on

that;s correct the seeders had partial data. just create a new user, however issue fixed in edit.blade.php 8f8d922e30cb0f1e0fe6e1a01dff054c3544b785
