### ISSUE TITLE
Request..

### ISSUE THREAD

**Issue by sachinraj07** [4jean/lav_sms#38]
Will these features be available?

The Noticeboard/Calendar in the Dashboard Area
Librarian/Acountant user pages
Library Resources/Study Materials Upload for Students

**Comment by yungifez** [comment]
Well he kinda looks busy for this 

I built something a basic notice board on my test version of this project trying to mimick this project 

I don't know how this open source thing works because I'm still new to it.  

The only problem is that the creator seems very busy to accept or reject pull requests
